language: objective-c
osx_image: xcode7
before_install:
 - brew update
 - brew install carthage
branches:
 only:
 - develop
xcode_project: Cast.xcodeproj
xcode_scheme: Cast

script:
- carthage bootstrap
- xctool -project Cast.xcodeproj -scheme Cast
