language: objective-c
before_install:
 - brew update
 - brew install carthage
branches:
 only:
 - master
xcode_project: Cast.xcodeproj
xcode_scheme: Cast
osx_image: beta-xcode7

script:
- carthage bootstrap
- xctool -project Cast.xcodeproj -scheme Cast
