language: objective-c
osx_image: xcode7
before_install:
 - brew update
 - brew install carthage
 - carthage bootstrap --verbose --platform mac
xcode_project: Cast.xcodeproj
xcode_scheme: Cast
