language: objective-c
osx_image: xcode7
before_install:
  - brew update
  - brew install carthage
  - brew install swiftlint
  - carthage bootstrap --platform mac
xcode_project: Cast.xcodeproj
xcode_scheme: Cast (Standard)
branches:
  only:
    - develop
script:
  xctool -project Cast.xcodeproj -scheme "Cast (Standard)" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
notifications:
  email: true
  slack: false
