language: objective-c
osx_image: beta-xcode6.3
cache:
  directories:
    - Lib/vendor/bundle
install:
  - (cd Lib && bundle install --path=vendor/bundle --binstubs=vendor/bin)
script:
  - (cd Lib && bundle exec rake test:ios test:osx)
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
